package exercise1;

import javax.annotation.processing.Generated;
import java.util.concurrent.atomic.AtomicInteger;

public class PlayerAndGame {
    // INSTANCE VARIABLES
    // =============================================================

    // Game Table
    private int gameId;
    private String gameTitle;


    // Player table
    private int playerId;
    private String firstName;
    private String lastName;
    private String address;
    private String postalCode;
    private String province;
    private String phoneNumber;


    // PlayerAndGame table
    private int playerAndGameId;
    private String playingDate;
    private String score;
    private static final AtomicInteger count = new AtomicInteger(0);
    private boolean isFilled;


    // CONSTRUCTOR
    // =============================================================================================
    public PlayerAndGame(int gameId,String gameTitle, int playerId, String firstName, String lastName, String address,
                         String postalCode, String province, String phoneNumber,String playingDate, String score) {

        // =====playerAndGameId is autogenerated and autoincremented, so no need to add it's setter==========

        setGameId(gameId);
        setGameTitle(gameTitle);
        setPlayerId(playerId);
        setFirstName(firstName);
        setLastName(lastName);
        setAddress(address);
        setPostalCode(postalCode);
        setProvince(province);
        setPhoneNumber(phoneNumber);
        setPlayingDate(playingDate);
        setScore(score);


    }

    // PUBLIC PROPERTIES
    // =============================================================================================
    // NOTE: only getters to prevent breaking of referential integrity

    // Game table getter and setter

    public void setGameId(int gameId){
        this.gameId = gameId;
    }

    public int getGameId() {
        return gameId;
    }

    public String getGameTitle() {
        return gameTitle;
    }

    public void setGameTitle(String gameTitle) {
        this.gameTitle = gameTitle;
    }

    // Player table getter and setter

    public void setPlayerId(int playerId){
        this.playerId = playerId;
    }

    public int getPlayerId() {
        return playerId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    // PlayerAndGame table getter and setter
    public int getPlayerGameId() {
        return playerAndGameId;
    }

    public String getPlayingDate() {
        return playingDate;
    }

    public String getScore() {
        return score;
    }

    //public void setPlayerGameId(int playerGameId) {
    //this.playerAndGameId = playerGameId;
    // }

    public void setPlayingDate(String playingDate) {

        this.playingDate = playingDate;
    }

    public void setScore(String score) {
        this.score = score;
    }


}
